# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-21 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('correct_file', models.FileField(upload_to='files')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(blank=True, null=True)),
                ('passed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CheckLogEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('text', models.CharField(max_length=300)),
                ('check_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creocheck.Check')),
            ],
        ),
        migrations.CreateModel(
            name='CheckTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('progress', models.FloatField(default=0)),
                ('done', models.BooleanField(default=False)),
                ('error', models.BooleanField(default=False)),
                ('passed', models.BooleanField(default=False)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creocheck.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='CheckTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('check_func', models.CharField(choices=[('MassPropChecker', 'MassPropChecker'), ('ModelTreeChecker', 'ModelTreeChecker'), ('RegenChecker', 'RegenChecker'), ('MacroRunner', 'MacroRunner'), ('SaveMetadata', 'SaveMetadata'), ('SleepOneSecond', 'SleepOneSecond')], max_length=50)),
                ('checkparams', models.TextField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creocheck.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='CheckUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MacroTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('macro', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=150, null=True)),
                ('file', models.FileField(upload_to='files')),
                ('metadata', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='checktask',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creocheck.UploadFile'),
        ),
        migrations.AddField(
            model_name='checktask',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creocheck.CheckUser'),
        ),
        migrations.AddField(
            model_name='check',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creocheck.CheckTask'),
        ),
        migrations.AddField(
            model_name='check',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creocheck.CheckTemplate'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creocheck.AssignmentCollection'),
        ),
    ]
