# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-04 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creocheck', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='checktask',
            options={'ordering': ['-passed', '-created']},
        ),
        migrations.AddField(
            model_name='assignment',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
    ]
